<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="khepera4_lrf">
<xacro:macro name="khepera_wheel" params="prefix offset_dir">
  <!-- offset_dir should be -1 for right weel, 1 for left wheel -->

  <link name="${prefix}_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="-1.570796 0 -1.5708"/>
      <geometry>
        <cylinder radius="0.021" length="0.003"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="-1.570796 0 -1.5708"/>
      <geometry>
        <cylinder radius="0.021" length="0.003"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="-1.570796 0 -1.5708"/>
      <mass value="0.1"/>
      <inertia ixx="${1/12*0.1*(3*.021*.021+.0059*.0059)}" ixy="0.0" ixz="0.0" iyy="${1/12*0.1*(3*.021*.021+.0059*.0059)}" iyz="0.0" izz="${1/2*0.1*.021*.021}"/>
    </inertial>
  </link>

  <joint name="base_to_${prefix}_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="${prefix}_wheel"/>
    <axis xyz="-1 0 0"/>
    <limit effort="10" velocity="47.61"/>
    <origin xyz="0 ${offset_dir*0.0527} 0.021" rpy="1.570796 0 -1.570796"/>
  </joint>

</xacro:macro>
</robot>

