<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">
<xacro:macro name="khepera_caster_wheel" params="prefix offset_dir">
  <!-- offset_dir should be -1 for rear caster weel, 1 for front caster wheel -->

  <link name="${prefix}_caster_wheel">
    <visual>
      <geometry>
        <sphere radius="0.005"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.005"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_to_${prefix}_caster_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="${prefix}_caster_wheel"/>
    <origin xyz="${offset_dir*0.05} 0 0.00505" rpy="1.570796 0 -1.570796"/>
  </joint>

</xacro:macro>
</robot>

